/*
 *  antsfiles
 */
package fr.antsfiles.pdftotable.view;

/**
 *
 */
public class DebitCreditPanel extends javax.swing.JPanel {

    /**
     * Creates new form DebitCreditPanel
     */
    public DebitCreditPanel() {
        initComponents();
    }

    public void updateDebitCredit(double totalDebit, double totalCredit) {
        jLabelTotalCredit.setText(String.format("%.02f", totalCredit));
        jLabelTotalDebit.setText(String.format("%.02f", totalDebit));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotalDebit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotalCredit = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jLabel2.setText("Total Credit:");
        jPanel1.add(jLabel2);

        jLabelTotalDebit.setText("---");
        jPanel1.add(jLabelTotalDebit);

        jLabel3.setText("Total Debit:");
        jPanel1.add(jLabel3);

        jLabelTotalCredit.setText("---");
        jPanel1.add(jLabelTotalCredit);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTotalCredit;
    private javax.swing.JLabel jLabelTotalDebit;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
