/*
 *  antsfiles
 */
package fr.antsfiles.pdftotable.view;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 */
public class SoldePanel extends javax.swing.JPanel {

    private double totalDebit;
    private double totalCredit;

    /**
     * Creates new form SoldePanel
     */
    public SoldePanel() {
        initComponents();
    }

    public void setTotalDebit(double totalDebit) {
        this.totalDebit = totalDebit;
    }

    public void setTotalCredit(double totalCredit) {
        this.totalCredit = totalCredit;
    }

    public void updateSoldeAfter() {
        if (jTextFieldSoldeBefore.getText().isBlank()) {
            jTextFieldSoldeBefore.setText("0");
        }
        double before = Double.parseDouble(jTextFieldSoldeBefore.getText().replace(",", "."));
        double after = before + totalCredit - totalDebit;

        DecimalFormatSymbols symbols = DecimalFormatSymbols.getInstance();
        symbols.setGroupingSeparator(' ');
        DecimalFormat formatter = new DecimalFormat("### ###.##", symbols);
        jLabelSoldeAfter.setText(formatter.format(after));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSoldeBefore = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelSoldeAfter = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jLabel5.setText("Solde before:");
        jPanel1.add(jLabel5);

        jTextFieldSoldeBefore.setText("0");
        jTextFieldSoldeBefore.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldSoldeBeforeCaretUpdate(evt);
            }
        });
        jTextFieldSoldeBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoldeBeforeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSoldeBefore);

        jLabel6.setText("Solde after:");
        jPanel1.add(jLabel6);

        jLabelSoldeAfter.setText("0");
        jPanel1.add(jLabelSoldeAfter);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSoldeBeforeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldSoldeBeforeCaretUpdate
        updateSoldeAfter();
    }//GEN-LAST:event_jTextFieldSoldeBeforeCaretUpdate

    private void jTextFieldSoldeBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoldeBeforeActionPerformed
        updateSoldeAfter();
    }//GEN-LAST:event_jTextFieldSoldeBeforeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSoldeAfter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldSoldeBefore;
    // End of variables declaration//GEN-END:variables
}
